version: '3.5'

services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    restart: always
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - 5432:5432